<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitebc6b51f42683abe7d4144cf55a3a59f
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Composer\\CaBundle\\' => 18,
        ),
        'A' => 
        array (
            'Abraham\\TwitterOAuth\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Composer\\CaBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/ca-bundle/src',
        ),
        'Abraham\\TwitterOAuth\\' => 
        array (
            0 => __DIR__ . '/..' . '/abraham/twitteroauth/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitebc6b51f42683abe7d4144cf55a3a59f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitebc6b51f42683abe7d4144cf55a3a59f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitebc6b51f42683abe7d4144cf55a3a59f::$classMap;

        }, null, ClassLoader::class);
    }
}
