<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'abraham/twitteroauth' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '55dcddb3bb8e87325acab2f219c08750b68efb74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../abraham/twitteroauth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.3.2',
            'version' => '1.3.2.0',
            'reference' => 'fd5dd441932a7e10ca6e5b490e272d34c8430640',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
